//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace SilverlightApplication1.DemoProxy {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DemoProxy.ClientesControllerSoap")]
    public interface ClientesControllerSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetClientes", ReplyAction="*")]
        System.IAsyncResult BeginGetClientes(SilverlightApplication1.DemoProxy.GetClientesRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightApplication1.DemoProxy.GetClientesResponse EndGetClientes(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientes", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightApplication1.DemoProxy.GetClientesRequestBody Body;
        
        public GetClientesRequest() {
        }
        
        public GetClientesRequest(SilverlightApplication1.DemoProxy.GetClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClientesRequestBody {
        
        public GetClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightApplication1.DemoProxy.GetClientesResponseBody Body;
        
        public GetClientesResponse() {
        }
        
        public GetClientesResponse(SilverlightApplication1.DemoProxy.GetClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SilverlightApplication1.DemoProxy.ArrayOfString GetClientesResult;
        
        public GetClientesResponseBody() {
        }
        
        public GetClientesResponseBody(SilverlightApplication1.DemoProxy.ArrayOfString GetClientesResult) {
            this.GetClientesResult = GetClientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesControllerSoapChannel : SilverlightApplication1.DemoProxy.ClientesControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightApplication1.DemoProxy.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightApplication1.DemoProxy.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesControllerSoapClient : System.ServiceModel.ClientBase<SilverlightApplication1.DemoProxy.ClientesControllerSoap>, SilverlightApplication1.DemoProxy.ClientesControllerSoap {
        
        private BeginOperationDelegate onBeginGetClientesDelegate;
        
        private EndOperationDelegate onEndGetClientesDelegate;
        
        private System.Threading.SendOrPostCallback onGetClientesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ClientesControllerSoapClient() {
        }
        
        public ClientesControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetClientesCompletedEventArgs> GetClientesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication1.DemoProxy.ClientesControllerSoap.BeginGetClientes(SilverlightApplication1.DemoProxy.GetClientesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClientes(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetClientes(System.AsyncCallback callback, object asyncState) {
            SilverlightApplication1.DemoProxy.GetClientesRequest inValue = new SilverlightApplication1.DemoProxy.GetClientesRequest();
            inValue.Body = new SilverlightApplication1.DemoProxy.GetClientesRequestBody();
            return ((SilverlightApplication1.DemoProxy.ClientesControllerSoap)(this)).BeginGetClientes(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApplication1.DemoProxy.GetClientesResponse SilverlightApplication1.DemoProxy.ClientesControllerSoap.EndGetClientes(System.IAsyncResult result) {
            return base.Channel.EndGetClientes(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private SilverlightApplication1.DemoProxy.ArrayOfString EndGetClientes(System.IAsyncResult result) {
            SilverlightApplication1.DemoProxy.GetClientesResponse retVal = ((SilverlightApplication1.DemoProxy.ClientesControllerSoap)(this)).EndGetClientes(result);
            return retVal.Body.GetClientesResult;
        }
        
        private System.IAsyncResult OnBeginGetClientes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetClientes(callback, asyncState);
        }
        
        private object[] OnEndGetClientes(System.IAsyncResult result) {
            SilverlightApplication1.DemoProxy.ArrayOfString retVal = this.EndGetClientes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClientesCompleted(object state) {
            if ((this.GetClientesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClientesCompleted(this, new GetClientesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClientesAsync() {
            this.GetClientesAsync(null);
        }
        
        public void GetClientesAsync(object userState) {
            if ((this.onBeginGetClientesDelegate == null)) {
                this.onBeginGetClientesDelegate = new BeginOperationDelegate(this.OnBeginGetClientes);
            }
            if ((this.onEndGetClientesDelegate == null)) {
                this.onEndGetClientesDelegate = new EndOperationDelegate(this.OnEndGetClientes);
            }
            if ((this.onGetClientesCompletedDelegate == null)) {
                this.onGetClientesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClientesCompleted);
            }
            base.InvokeAsync(this.onBeginGetClientesDelegate, null, this.onEndGetClientesDelegate, this.onGetClientesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightApplication1.DemoProxy.ClientesControllerSoap CreateChannel() {
            return new ClientesControllerSoapClientChannel(this);
        }
        
        private class ClientesControllerSoapClientChannel : ChannelBase<SilverlightApplication1.DemoProxy.ClientesControllerSoap>, SilverlightApplication1.DemoProxy.ClientesControllerSoap {
            
            public ClientesControllerSoapClientChannel(System.ServiceModel.ClientBase<SilverlightApplication1.DemoProxy.ClientesControllerSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetClientes(SilverlightApplication1.DemoProxy.GetClientesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetClientes", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApplication1.DemoProxy.GetClientesResponse EndGetClientes(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApplication1.DemoProxy.GetClientesResponse _result = ((SilverlightApplication1.DemoProxy.GetClientesResponse)(base.EndInvoke("GetClientes", _args, result)));
                return _result;
            }
        }
    }
}
